### ISSUE TITLE
Great results! Looking forward to the code release. Might I ask when are you going to release the code?

### ISSUE THREAD

**Issue by DrXuQian** [IST-DASLab/WoodFisher#1]

**Comment by sidak** [comment]
Hi @DrXuQian! Thanks for your interest and patience. 

The current plan is to have the code released by the end of this month or so. 

In the meanwhile, if you have any particular questions, let us know. 

Best,
Sidak

**Comment by DrXuQian** [comment]
Hi @sidak , any news on the release of the code. I tried to implement the code but failed to reproduce the paper's results. Kind of waiting to see what I got wrong there. ; )

**Comment by sidak** [comment]
Hi! Thanks for your patience, sorry I have just been quite busy with other things. In any case, I am mostly done with the refactoring, and code should be out in atmost a couple of weeks from now. 

Stay tuned! 
Sidak

**Comment by sidak** [comment]
At last, the code is released! 😄  Thanks for your patience.

Let us know if you have more questions. I will close this issue now. 

Sidak
