### ISSUE TITLE
CUDA out of memory when calculating the inverse of hessian

### ISSUE THREAD

**Issue by DrXuQian** [IST-DASLab/WoodFisher#2]
**Issue:**
It says 
"RuntimeError: CUDA out of memory. Tried to allocate 2422923.30 GiB (GPU 0; 47.46 GiB total capacity; 497.30 MiB already allocated; 43.16 GiB free; 3.41 GiB reserved in total by PyTorch)" 
when calculating the following line:
"WoodFisher/pruners/woodfisher.py", line 140, in _compute_woodburry_fisher_inverse
    `self._fisher_inv = torch.ger(sample_grads, sample_grads).mul_(1.0 / numerator_normalization).div_(`

It seems like torch.ger function would pre-allocate a lot of memory. And sample_grads would flatten all the grads of weights. So this would consume a lot of memory. 
The cmd line I used to generate this is:
python main.py --dset_path ./data/ --arch resnet50 --config_path ./configs/resnet50.yaml --batch_size 256 --pretrained --prune-end 20
Any clues on this? Am I missing some parameters for this?

**Comment by sidak** [comment]
Hi! 

So first of all, I would ask you to please check out the README, in particular, the section on ``Memory Management``. 

For a model like ResNet50, you have to use *blockwise version of WoodFisher*. You can invoke that by `--prune-class woodfisherblock`, and control the size of blocks by `--fittable-params 1000` (for e.g., 1000 here). If this is still an issue depending on your machine  configuration, use `--offload-inv --offload-grads` to offload some memory onto CPU. 

Also, I would recommend you to take a look at the example scripts. For instance, this one: https://github.com/IST-DASLab/WoodFisher/blob/main/scripts/resnet50_woodfisher_sparsity-0.9.sh. 

Best,
Sidak
